CREATE TABLE IF NOT EXISTS CC_COURSES (
    COURSE_CODE VARCHAR(10) PRIMARY KEY,
    COURSE_DESC VARCHAR(255),
    CAMPUS VARCHAR(25)
);

CREATE TABLE IF NOT EXISTS CC_TAKEN_COURSE (
    ID UUID REFERENCES CC_CREDENTIALS(ID),
    COURSE_CODE VARCHAR(10) REFERENCES CC_COURSES(COURSE_CODE),
    PRIMARY KEY (ID,COURSE_CODE)
);


