CREATE TABLE IF NOT EXISTS CC_CREDENTIALS (
    ID UUID PRIMARY KEY, 
    EMAIL TEXT NOT NULL,
    HASH CHAR(60) NOT NULL
);
CREATE TABLE IF NOT EXISTS CC_USER_INFO (
    ID UUID REFERENCES CC_CREDENTIALS(ID),
    ROLE VARCHAR(10) NOT NULL,
    FNAME VARCHAR(25) NOT NULL,
    LNAME VARCHAR(40),
    PROGRAM VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS CC_KNOWN_IPS (
    IP INET PRIMARY KEY,
    ID UUID REFERENCES CC_CREDENTIALS(ID)
);


